### ISSUE TITLE
Jumpstart onboarding bug

### ISSUE THREAD

**Issue by samuelandert** [omoearth/omo-li#132]
I just tried to send 1 invite credit with the following link:
https://omo.li/#/empowerMe/0x23B5B134AF68d6729b9cEA617EdBB28f0E5292E4

In the UI I got the following bug:
<img width="720" alt="Bildschirmfoto 2020-12-12 um 07 11 39" src="https://user-images.githubusercontent.com/747161/101977072-39828180-3c4b-11eb-834a-cf99c59f0ef4.png">

The console doesn't give me any feedback

**Comment by jaensen** [comment]
This happens only when you're pasting the link directly in a new browser tab. In this case you're not yet authenticated and therefore have no access to your safe key. To solve this, the start of the Jumpstart-Process must be delayed until the authentication is completed.

As a temporary workaround you can paste the link into  a tab in which you're already authenticated.
