### ISSUE TITLE
auto deploy to fission from live branch

### ISSUE THREAD

**Issue by samuelandert** [omoearth/omo-li#57]

**Comment by walkah** [comment]
Good news! I am actively working on a github action over here: https://github.com/fission-suite/publish-action 

You can see a sample run here: https://github.com/walkah/fission-notes/runs/1685464000?check_suite_focus=true

**Comment by samuelandert** [comment]
Oh, very nice!

**Comment by samuelandert** [comment]
Very cool! Work perfectly!
